services:
  - type: web
    name: my-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
    build:
      packages:
        - google-chrome-stable
